config/routes.rb
Rails.application.routes.draw do

  root to: 'enquiries#new'

  resources :enquiries, only: [:new, :create]
  resources :invitations, only: [:new, :create]
  resources :users, only: [:new, :create]

  resources :orders, only: [:new, :create]

  namespace :admin do
    resources :users, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :people, inverse_of: :group

  validates :name, presence: true

end

app/models/invitation.rb
class Invitation

  include ActiveModel::Model

  attr_accessor :name, :email

  validates :name, :email, presence: true
  validate :user_already_registered

  private

  def user_already_registered
    errors.add(email: 'already registered') if Person.exists?(email: email)
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :order, inverse_of: :line_items

  validates :description, :quantity, :unit_price, :sub_total, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, :sub_total, numericality: { greater_than: 0 }

  before_validation :calculate_sub_total

  private

  def calculate_sub_total
    return if quantity.blank? || unit_price.blank?
    self.sub_total = quantity * unit_price
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :person, inverse_of: :orders

  has_many :line_items, inverse_of: :order

  validates :order_no, :shipping_address, presence: true

  before_validation :calculate_grand_total

  accepts_nested_attributes_for :line_items

  private

  def calculate_grand_total
    self.grand_total = line_items.map(&:sub_total).reject(&:blank?).sum
  end

end

app/models/person.rb
class Person < ApplicationRecord

  belongs_to :group, inverse_of: :people, optional: true

  has_many :orders, inverse_of: :person

  validates :email, :name, presence: true
  validates :password, presence: true, confirmation: true

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @form = Admin::UserSearchForm.new(admin_user_search_form_params)
    @form.submit if params[:admin_user_search_form].present?
  end

  private

  def admin_user_search_form_params
    params.fetch(:admin_user_search_form, {}).permit(:term, :status, :group)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController

  def new
    @form = ContactForm.new
  end

  def create
    @form = ContactForm.new(contact_form_params)
    if @form.submit
      redirect_to root_path, notice: 'Thank you for your enquiry'
    else
      render :new
    end
  end

  private

  def contact_form_params
    params.require(:contact_form).permit(:name, :email, :message)
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  def new
    @form = UserInvitationForm.new
  end

  def create
    @form = UserInvitationForm.new(user_invitation_form_params)
    if @form.submit
      redirect_to root_path, notice: 'Thank you for your enquiry'
    else
      render :new
    end
  end

  private

  def user_invitation_form_params
    params.require(:user_invitation_form).permit(invitations_attributes: [:name, :email])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :prepare_person

  def new
    @form = OrderForm.new(@person)
  end

  def create
    @form = OrderForm.new(@person, order_form_params)
    if @form.submit
      redirect_to root_path, notice: 'Thank you for your order'
    else
      render :new
    end
  end

  private

  def prepare_person
    @person = Person.first # this is just an example, ideally you'd use the current_user or something
  end

  def order_form_params
    params.require(:order_form).permit(
      :sign_up_for_newsletter,
      :billing_address,
      :shipping_address,
      :shipping_same_as_billing_address,
      line_items_attributes: [:description, :quantity, :unit_price]
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @form = UserRegistrationForm.new
  end

  def create
    @form = UserRegistrationForm.new(user_registration_form_params)
    if @form.submit
      redirect_to root_path, notice: 'Thank you for your registration'
    else
      render :new
    end
  end

  private

  def user_registration_form_params
    params.require(:user_registration_form).permit(:terms_of_service, person_attributes: [:name, :email, :password, :password_confirmation])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/users/index.html.slim
= simple_form_for @form, url: admin_users_path, method: :get do |f|

  = f.input :term
  = f.input :status, collection: @form.options_for_status, include_blank: 'Any status'
  = f.input :group, collection: @form.options_for_group, include_blank: 'Any group'

  = f.submit 'Search'

ul
  - @form.results.each do |person|
    li = person.inspect

app/views/enquiries/new.html.slim
= simple_form_for @form, url: enquiries_path do |f|

  = f.input :email
  = f.input :name
  = f.input :message, as: :text

  = f.submit

app/views/invitations/new.html.slim
= simple_form_for @form, url: invitations_path do |f|

  = f.simple_fields_for :invitations do |invitation_fields|
    = invitation_fields.input :name
    = invitation_fields.input :email

  = f.submit 'Send'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormObjectSeries</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.slim
= simple_form_for @form, url: orders_path do |f|

  = f.input :shipping_address

  = f.input :shipping_same_as_billing_address, as: :boolean

  = f.input :billing_address

  = f.simple_fields_for :line_items do |line_items_fields|

    = line_items_fields.input :description
    = line_items_fields.input :quantity
    = line_items_fields.input :unit_price

  = f.submit 'Place Order'

app/views/users/new.html.slim
= simple_form_for @form, url: users_path do |f|

  = f.input :terms_of_service, as: :boolean

  = f.simple_fields_for :person do |person_fields|
    = person_fields.input :name
    = person_fields.input :email
    = person_fields.input :password
    = person_fields.input :password_confirmation

  = f.submit